export { default as About } from './about/About'
export { default as Content } from './content/Content'
export { default as Footer } from './footer/Footer'
export { default as Header } from './header/Header'
export { default as Info } from './info/Info'