export { default as Article } from './article/Article'
export { default as CTA } from './cta/CTA'
export { default as Front } from './front/Front'
export { default as Navbar } from './navbar/Navbar'
export { default as Profile } from './profile/Profile'